### ISSUE TITLE
TypeError: unicode argument expected, got 'str'

### ISSUE THREAD

**Issue by dy-lin** [plantismash/plantismash#1]
I seem to be having some trouble setting up the database object. Here is **first** _condensed_ instance of the TypeError. The **rest** of them can be viewed in the error log file:
[error2.log](https://github.com/plantismash/plantismash/files/3444529/error2.log)

I am using Python2.7, and have installed any missing requirements:
```
pip install -r requirements.txt
pip install minimock
```

TypeError:
```
$ make
nosetests -v
test generate_namespace() method ... ERROR
======================================================================
ERROR: test generate_namespace() method
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/projects/btl/dlin/bin/plantismash/antismash/db/biosql/test/test_db.py", line 50, in setUp
    mydb = db.aSDB(self.options)
  File "/projects/btl/dlin/bin/plantismash/antismash/db/biosql/__init__.py", line 69, in __init__
    raise e
TypeError: unicode argument expected, got 'str'
-------------------- >> begin captured logging << --------------------
root: ERROR: Error setting up the database object; Check parameters in default.cfg
Traceback (most recent call last):
  File "/projects/btl/dlin/bin/plantismash/antismash/db/biosql/__init__.py", line 66, in __init__
    db=options.BioSQLconfig.dbdb)
  File "/projects/btl/dlin/bin/backup/miniconda3/envs/plantismash/lib/python2.7/site-packages/minimock.py", line 521, in __call__
    self.mock_tracker.call(self.mock_name, *args, **kw)
  File "/projects/btl/dlin/bin/backup/miniconda3/envs/plantismash/lib/python2.7/site-packages/minimock.py", line 317, in call
    self.file.write(msg)
TypeError: unicode argument expected, got 'str'
--------------------- >> end captured logging << ---------------------
```

In addition to the TypeError, there are some AssertionErrors downstream. In general:
```
----------------------------------------------------------------------
Ran 107 tests in 8.022s

FAILED (SKIP=8, errors=26, failures=7)
make: *** [unit] Error 1
```

**Comment by KristinaGagalova** [comment]
Hi, 
Thank you in advance for your help. We haven't had much luck running plantiSMASH so far. Any input from your side will be great!

**Comment by satriaphd** [comment]
hi, can you elaborate the steps you've taken to produce this error?
have you tried to just run 'python2 run_antismash.py'?

**Comment by dy-lin** [comment]
Sure-- here are the actual full steps:

```
$ git clone git@github.com:plantismash/plantismash.git
$ cd plantismash
$ pip install -r requirements.txt
$ pip install minimock
$ make
```

I only ran `make` because your repo contains a `Makefile` (no other reason). If it is not required to run the `Makefile`, does `run_antismash.py` contain the whole `plantismash` pipeline? However, running `run_antismash.py` gives me the errors I described above.

**Comment by sunnycqcn** [comment]
Hi,
I met the similar error using gbk format data.
Thanks,
Fuyou

**Comment by KristinaGagalova** [comment]
Hi, 
Could you provide clear instructions on the installation? 
That will be of great help 
Thank you in advance
